### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by ccccler** [Dafeigy/ChartsGPT#5]
大神啊，我照你的教程，在根目录建了一个config，然后把api替换成了自己的api，但是运行网页之后就是报错啊。这是怎么回事呢？
![image](https://github.com/Dafeigy/ChartsGPT/assets/127079609/4efe6634-1ed5-408b-ac6c-30912c938d9f)
![image](https://github.com/Dafeigy/ChartsGPT/assets/127079609/831c6762-7006-4251-b77c-d0e57b462b44)

**Comment by Dafeigy** [comment]
Hello, thanks for your issue report. This bug is related to the return data from ChatGPT in un-formatted json, which means the return data should be satisfied json format but failed. 

I am not a expert in prompt enginerting, so I can't actually make some influence on leading ChatGPT returns a formatted json data. However, if you have some skill in prompt engineering, you can change the prompt in  `utils.py` ：
```python
self.messages = [
            {"role": "system", 
             "content": 
                """根据需求，直接返回提供兼容5.2.1版本的ECharts options符合格式的JSON字符串,回复格式如下:{
                "title": {
                "left": 'center'
                },
                "tooltip": {
                },
                "legend": {
                "orient": 'vertical',
                "left": 'left'
                },
                "series": [],
                ...
                }，不需要说明解释返回内容，请严格遵循json语法返回。"""}
        ]
```
You can perform your prompt skill and change the prompt to make ChatGPT outputs data result that strictly satisfied json format.  I am sorry that urrently I am not going to fix that until Chinese New Year holiday due to my heavy burden on other projects.

By the way, your ChatGPT API key is EXPOSED and ANYONE who see this issue may USE it.
 
Please be careful of your privacy leak when reporting your issue.
